name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Main metrics
        uses: lowlighter/metrics@latest
        with:
          filename: dist/metrics.svg
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: anthhub
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugins_errors_fatal: no

      - name: Habits plugin
        uses: lowlighter/metrics@latest
        with:
          filename: dist/metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: anthhub
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          config_timezone: Asia/Shanghai
          plugins_errors_fatal: no

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
